import { ArrowLeft } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useEffect } from 'react'
import { getLesson } from '../data/lessons'
import { useLearnLab } from '../state/LearnLabProvider'
import { Mascot } from '../components/Mascot'
import { AreaPerimeter, Atoms, Cells, Fractions, LightShadow, Multiplication, ShapeExplorer, SolarSystem, StatesMatter, WaterCycle } from '../modules/LessonModules'
import { QuizCard, type Question } from '../components/QuizCard'

const quizBank: Record<string, Question[]> = {
  'area-perimeter': [{ prompt: 'A rectangle is 6 squares wide and 4 squares tall. What is its area?', options: ['10 square units', '24 square units', '20 square units'], answer: 1, hint: 'Count the rows and columns inside.' }, { prompt: 'Which path shows the perimeter?', options: ['The distance around the outside', 'The space inside', 'A diagonal across the shape'], answer: 0, hint: 'Perimeter is like walking around the fence.' }, { prompt: 'Which pair makes area 24?', options: ['3 × 8', '5 × 5', '2 × 10'], answer: 0, hint: 'Try multiplying each pair.' }],
  fractions: [{ prompt: 'A pizza is split into 4 equal pieces. You eat 3. What fraction is left?', options: ['1/4', '3/4', '4/3'], answer: 0, hint: 'One piece is still on the plate.' }, { prompt: 'Which fraction is the same as one half?', options: ['1/3', '2/4', '3/4'], answer: 1, hint: 'Two out of four is the same share as one out of two.' }, { prompt: 'What makes a fraction fair?', options: ['Equal-sized pieces', 'Lots of colors', 'The biggest piece first'], answer: 0, hint: 'Fractions need equal parts to be fair.' }],
  shapes: [{ prompt: 'A cube has an edge length of 3. What is its volume?', options: ['9 cubes', '27 cubes', '18 cubes'], answer: 1, hint: 'Multiply 3 × 3 × 3.' }, { prompt: 'What does surface area measure?', options: ['The outside faces', 'The space inside', 'Only the bottom face'], answer: 0, hint: 'Watch the solid unfold into a net.' }, { prompt: 'A rectangular prism is 4 × 3 × 2. What is its volume?', options: ['9 cubes', '24 cubes', '12 cubes'], answer: 1, hint: 'Count one layer, then count the layers.' }],
  multiplication: [{ prompt: 'What is 5 groups of 3?', options: ['8', '15', '53'], answer: 1, hint: 'Count five rows of three.' }, { prompt: 'Which addition matches 3 × 4?', options: ['3 + 3 + 3 + 3', '4 + 4 + 4', 'Both A and B'], answer: 2, hint: 'Groups can be counted by either number.' }, { prompt: 'What does the × sign remind us of?', options: ['Equal groups', 'A shape corner', 'A subtraction'], answer: 0, hint: 'Multiplication is a shortcut for equal groups.' }],
  'solar-system': [{ prompt: 'Which planet is our home?', options: ['Mars', 'Earth', 'Jupiter'], answer: 1, hint: 'Look for the blue planet.' }, { prompt: 'What do planets travel around?', options: ['The Moon', 'A cloud', 'The Sun'], answer: 2, hint: 'The Sun is the star at the center.' }, { prompt: 'Which planet is famous for its rings?', options: ['Saturn', 'Venus', 'Mercury'], answer: 0, hint: 'Its rings make it easy to spot.' }],
  'water-cycle': [{ prompt: 'What warms water so it can rise as vapor?', options: ['The Sun', 'A snowflake', 'The wind only'], answer: 0, hint: 'The Sun gives water energy.' }, { prompt: 'What do clouds do when drops get heavy?', options: ['Rain', 'Disappear forever', 'Turn into rocks'], answer: 0, hint: 'Drops fall back down to Earth.' }, { prompt: 'Where can water collect?', options: ['Oceans and lakes', 'Only in the sky', 'Inside a star'], answer: 0, hint: 'Collection happens on the ground.' }],
  'states-of-matter': [{ prompt: 'Which state keeps its own shape?', options: ['Solid', 'Liquid', 'Gas'], answer: 0, hint: 'Think of an ice cube.' }, { prompt: 'In which state do particles spread far apart?', options: ['Solid', 'Liquid', 'Gas'], answer: 2, hint: 'Gas particles have room to zoom.' }, { prompt: 'What happens as a solid gets warmer?', options: ['Its particles move more', 'It becomes heavier', 'It stops moving'], answer: 0, hint: 'Warmth gives particles energy.' }],
  atoms: [{ prompt: 'Which tiny particle tells us the name of an element?', options: ['Protons', 'Electrons', 'Clouds'], answer: 0, hint: 'Count the red particles in the atom’s centre.' }, { prompt: 'Where do electrons move?', options: ['Around the nucleus', 'Inside a leaf only', 'At the bottom of the ocean'], answer: 0, hint: 'Look at the glowing dots on the shells.' }, { prompt: 'Which element is part of the air we breathe?', options: ['Oxygen', 'Gold', 'Wood'], answer: 0, hint: 'It is shown with the letter O.' }],
  cells: [{ prompt: 'What are cells?', options: ['Tiny living building blocks', 'Little planets', 'Kinds of weather'], answer: 0, hint: 'Plants, animals, and you are all made from them.' }, { prompt: 'Which part is the cell’s control room?', options: ['Nucleus', 'Vacuole', 'Cell wall'], answer: 0, hint: 'It carries the cell’s directions.' }, { prompt: 'Which cell has chloroplasts?', options: ['Plant cell', 'Animal cell', 'Neither cell'], answer: 0, hint: 'Chloroplasts use sunlight to make plant food.' }],
  'light-shadow': [{ prompt: 'What happens to a shadow when an object moves closer to the lamp?', options: ['It grows', 'It vanishes', 'It stays exactly the same'], answer: 0, hint: 'Try sliding the object toward the light.' }, { prompt: 'What does a shadow need?', options: ['Light, an object, and a surface', 'Only darkness', 'A mirror'], answer: 0, hint: 'Something must block the light.' }, { prompt: 'Light usually travels in…', options: ['Curvy loops', 'Straight lines', 'Zigzags'], answer: 1, hint: 'Imagine tiny arrows leaving the lamp.' }],
}

const lessonGuides: Record<string, { notice: string; why: string; try: string }> = {
  'area-perimeter': { notice: 'Squares fill the inside; a glowing dot travels around the edge.', why: 'Area tells how much space is inside. Perimeter tells how far it is around.', try: 'Make the same area with two different rectangles.' },
  fractions: { notice: 'Every slice must be the same size for the share to be fair.', why: 'The bottom number tells how many equal parts there are. The top number tells how many are chosen.', try: 'Choose a fraction, then tap each piece you can count.' },
  shapes: { notice: 'Volume builds the inside with cubes. Surface area opens the outside into faces.', why: 'Changing a measurement changes both the space a solid holds and the covering it needs.', try: 'Pause the net and count every outside face.' },
  multiplication: { notice: 'Each row is an equal group, so it can be counted quickly.', why: 'Multiplication is repeated addition with the same amount every time.', try: 'Change one control and say the addition sentence out loud.' },
  'solar-system': { notice: 'Every planet has a different colour, surface, and journey around the Sun.', why: 'Planets are worlds with their own features. Their order helps us understand our space neighbourhood.', try: 'Open a planet, rotate it, and find the clue in the panel.' },
  'water-cycle': { notice: 'The same water keeps moving: up as vapour, together in clouds, down as rain, then back to the lake.', why: 'The Sun provides energy. Cooling air gathers water into clouds, and gravity brings it down.', try: 'Play the full cycle, then pause at the step you can explain best.' },
  'states-of-matter': { notice: 'The particles stay the same; their spacing and movement change.', why: 'Heating gives particles more motion. Cooling slows them and pulls them closer together.', try: 'Move the slider slowly and watch for the moment the behaviour changes.' },
  atoms: { notice: 'The centre is called the nucleus. Electrons move around it in shells.', why: 'The number of protons is an element’s special ID—change it and you get a different element.', try: 'Pick two elements and compare their shells.' },
  cells: { notice: 'A cell is a tiny living workspace with different parts doing different jobs.', why: 'The nucleus guides the cell, mitochondria help release energy, and plant cells have extra food-making parts.', try: 'Tap a part, then look for the visual clue that matches its job.' },
  'light-shadow': { notice: 'The lamp sends light forward. The block stops part of it, leaving a dark shape on the screen.', why: 'The closer an object is to a lamp, the more the light spreads around it and the bigger its shadow becomes.', try: 'Turn on the rays, then drag the block toward and away from the lamp.' },
}

export function LessonPage() {
  const { lessonId } = useParams(); const lesson = getLesson(lessonId); const navigate = useNavigate(); const { markVisited } = useLearnLab()
  useEffect(() => { if (lesson) markVisited(lesson.id) }, [lesson, markVisited])
  if (!lesson) return <div className="page-width empty-page"><h1>That adventure wandered off.</h1><Link to="/subjects">Back to adventures</Link></div>
  const guide = lessonGuides[lesson.id]
  return <div className="lesson-page page-width"><div className="lesson-nav"><button className="back-link" onClick={() => navigate(-1)}><ArrowLeft size={15} /> Back to adventures</button></div><div className="lesson-heading"><div><span className={`lesson-subject-label ${lesson.subject}`}>{lesson.subject === 'math' ? 'Maths mission' : 'Science mission'} · {lesson.duration}</span><h1>{lesson.title}</h1><p>{lesson.tip}</p></div><Mascot message={lesson.id === 'area-perimeter' ? 'Move a measurement and watch the shape change.' : 'Change one thing and watch closely.'} compact /></div>{guide && <section className="lesson-guide" aria-label="How to explore this lesson"><div><span>Notice</span><p>{guide.notice}</p></div><div><span>Why it works</span><p>{guide.why}</p></div><div><span>Try next</span><p>{guide.try}</p></div></section>}<div className="lesson-stage"><ModuleSwitch id={lesson.id} /></div><QuizCard lessonId={lesson.id} questions={quizBank[lesson.id]} /><Link to={lesson.subject === 'math' ? '/subject/math' : '/subject/science'} className="lesson-end-link"><ArrowLeft size={15} /> Choose another {lesson.subject === 'math' ? 'maths' : 'science'} mission</Link></div>
}
function ModuleSwitch({ id }: { id: string }) { switch (id) { case 'area-perimeter': return <AreaPerimeter />; case 'fractions': return <Fractions />; case 'shapes': return <ShapeExplorer />; case 'multiplication': return <Multiplication />; case 'solar-system': return <SolarSystem />; case 'water-cycle': return <WaterCycle />; case 'states-of-matter': return <StatesMatter />; case 'atoms': return <Atoms />; case 'cells': return <Cells />; case 'light-shadow': return <LightShadow />; default: return null } }
